data_validation_size=data_size-train_data_size;
% disp('init_vali');
out=predictor(data_validation',...
    p,...
    train_data,...
    dimensions,...
    b*ones(1,data_validation_size));
errors=out~=data_validation(:,end)';
error=sum(errors);
error_por=[error_por,error/data_validation_size];